import { CodeEditor } from '../components/CodeEditor';
import { TraceTable } from '../components/TraceTable';
import { ConstraintViewer } from '../components/ConstraintViewer';
import { Explainer } from '../components/Explainer';
import { useStark } from '../contexts/StarkContext';
import { Link } from 'react-router-dom';

export function TracePage() {
    const { code, setCode, trace, regNames, air, failures, error, tamperTrace, resetTrace, resetCode } = useStark();

    return (
        <div className="container" style={{ paddingBottom: '100px' }}>
            <h1>1. Trace & AIR</h1>
            <p>
                This page demonstrates two distinct phases of the STARK protocol that happen
                at different times in a real system.
            </p>

            {/* Phase explanation banner */}
            <div style={{
                display: 'grid',
                gridTemplateColumns: '1fr 1fr',
                gap: '16px',
                marginTop: '24px',
                marginBottom: '24px',
            }}>
                <div style={{
                    padding: '16px',
                    background: 'rgba(100, 200, 255, 0.1)',
                    borderRadius: '8px',
                    borderLeft: '4px solid var(--accent-secondary)',
                }}>
                    <h4 style={{ margin: '0 0 8px 0', color: 'var(--accent-secondary)' }}>
                        Phase 1: Setup (Compile Time)
                    </h4>
                    <p style={{ margin: 0, fontSize: '0.9em' }}>
                        The <strong>AIR constraints</strong> are derived from the program structure.
                        These define what a valid execution looks like and are <em>public knowledge</em>.
                    </p>
                    <div style={{ marginTop: '8px', fontSize: '0.8em', color: 'var(--text-muted)' }}>
                        Done once per program by the protocol designer.
                    </div>
                </div>
                <div style={{
                    padding: '16px',
                    background: 'rgba(255, 180, 100, 0.1)',
                    borderRadius: '8px',
                    borderLeft: '4px solid var(--accent-tertiary)',
                }}>
                    <h4 style={{ margin: '0 0 8px 0', color: 'var(--accent-tertiary)' }}>
                        Phase 2: Proving (Run Time)
                    </h4>
                    <p style={{ margin: 0, fontSize: '0.9em' }}>
                        The <strong>Execution Trace</strong> is generated by actually running the computation.
                        This is the prover's <em>private witness</em>.
                    </p>
                    <div style={{ marginTop: '8px', fontSize: '0.8em', color: 'var(--text-muted)' }}>
                        Done each time someone proves a computation.
                    </div>
                </div>
            </div>

            <Explainer title="Why This Matters">
                <p>
                    In this toy app, we generate both the AIR and the trace from the same code
                    for convenience. But in a real STARK system:
                </p>
                <ul>
                    <li>
                        <strong>AIR</strong> is defined during <em>setup</em> — it encodes the rules
                        of the computation (e.g., "this is how Fibonacci works") and is made public.
                    </li>
                    <li>
                        <strong>Trace</strong> is generated during <em>proving</em> — it's the actual
                        execution (e.g., "here are the specific Fibonacci numbers I computed").
                    </li>
                </ul>
                <p style={{ marginTop: '12px' }}>
                    The prover proves: "I know a trace that satisfies the public AIR constraints."
                </p>
                <p style={{ marginTop: '8px', fontSize: '0.9em', color: 'var(--text-muted)' }}>
                    See <Link to="/implementation" style={{ color: 'var(--accent-primary)' }}>Implementation Details</Link> for
                    a complete breakdown of what's created when.
                </p>
            </Explainer>

            <Explainer title="What is an Execution Trace?">
                <p>
                    A STARK proof starts with an <strong>Execution Trace</strong>. This is a table where:
                </p>
                <ul>
                    <li>Each <strong>column</strong> represents a register (like <code>r0</code>, <code>r1</code>).</li>
                    <li>Each <strong>row</strong> represents one step of the computation (one clock cycle).</li>
                </ul>
                <p>
                    The prover wants to prove they know a valid trace that satisfies the program's logic.
                </p>
            </Explainer>

            <div style={{ marginBottom: '32px' }}>
                <details style={{
                    background: 'rgba(255,255,255,0.05)',
                    borderRadius: '8px',
                    border: '1px solid var(--border-color)',
                    padding: '12px'
                }}>
                    <summary style={{ cursor: 'pointer', fontWeight: 'bold' }}>DSL Reference (Click to Expand)</summary>
                    <div style={{ marginTop: '16px', paddingLeft: '16px' }}>
                        <p><strong>Registers:</strong> <code>r0, r1, r2, ...</code> (up to r9)</p>
                        <p><strong>Commands:</strong></p>
                        <ul style={{ lineHeight: '1.6' }}>
                            <li><code>prime 257</code>: Set the field prime (must be first). Use 257 for longer programs.</li>
                            <li><code>r0 = 1</code>: Initialize a register.</li>
                            <li><code>r0 = r1 + r2</code>: Addition.</li>
                            <li><code>r0 = r1 - r2</code>: Subtraction.</li>
                            <li><code>r0 = r1 * r2</code>: Multiplication.</li>
                            <li><code>repeat N: ...</code>: Repeat a block N times. Indent with 4 spaces.</li>
                            <li><code>halt</code>: End execution.</li>
                        </ul>
                        <p><strong>Note:</strong> All math is modular (modulo the prime).</p>
                    </div>
                </details>
            </div>

            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '24px', marginTop: '32px' }}>
                <div>
                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px' }}>
                        <h3>
                            Program
                            <span style={{
                                marginLeft: '8px',
                                fontSize: '0.7em',
                                padding: '2px 8px',
                                background: 'rgba(100, 200, 255, 0.2)',
                                borderRadius: '4px',
                                color: 'var(--accent-secondary)',
                            }}>
                                Setup Phase
                            </span>
                        </h3>
                        <button
                            className="btn btn-ghost"
                            onClick={resetCode}
                            style={{ fontSize: '0.8em', padding: '6px 12px' }}
                        >
                            Reset Code
                        </button>
                    </div>
                    <CodeEditor
                        value={code}
                        onChange={setCode}
                        error={error}
                    />
                </div>

                <div>
                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px' }}>
                        <h3>
                            Execution Trace
                            <span style={{
                                marginLeft: '8px',
                                fontSize: '0.7em',
                                padding: '2px 8px',
                                background: 'rgba(255, 180, 100, 0.2)',
                                borderRadius: '4px',
                                color: 'var(--accent-tertiary)',
                            }}>
                                Proving Phase
                            </span>
                        </h3>
                        <div style={{ display: 'flex', gap: '8px' }}>
                            <button
                                className="btn btn-ghost"
                                onClick={resetTrace}
                                style={{ fontSize: '0.8em', padding: '6px 12px' }}
                            >
                                Repair Trace
                            </button>
                            <button
                                className="btn btn-ghost"
                                onClick={tamperTrace}
                                style={{ fontSize: '0.8em', padding: '6px 12px', color: 'var(--accent-error)', borderColor: 'var(--accent-error)' }}
                            >
                                Corrupt Trace
                            </button>
                        </div>
                    </div>

                    {failures.length > 0 && (
                        <div className="alert error" style={{ marginBottom: '16px', padding: '12px' }}>
                            <strong>Warning:</strong> Trace is invalid! {failures.length} constraints violated.
                        </div>
                    )}

                    {trace.length > 0 ? (
                        <TraceTable trace={trace} regNames={regNames} />
                    ) : (
                        <div className="card muted">
                            No trace available. Fix errors to see execution.
                        </div>
                    )}
                </div>
            </div>

            {air && (
                <div style={{ marginTop: '32px' }}>
                    <div style={{
                        display: 'flex',
                        alignItems: 'center',
                        gap: '12px',
                        marginBottom: '16px',
                    }}>
                        <h2 style={{ margin: 0 }}>AIR Constraints</h2>
                        <span style={{
                            fontSize: '0.7em',
                            padding: '2px 8px',
                            background: 'rgba(100, 200, 255, 0.2)',
                            borderRadius: '4px',
                            color: 'var(--accent-secondary)',
                        }}>
                            Public (from Setup)
                        </span>
                    </div>
                    <p className="muted" style={{ marginBottom: '16px' }}>
                        These constraints are derived from the program structure and define what makes
                        an execution valid. The verifier knows these constraints; the prover must
                        demonstrate their trace satisfies them.
                    </p>
                    <ConstraintViewer air={air} failures={failures} />
                </div>
            )}
        </div>
    );
}
